### Register success
POST http://localhost:8080/api/auth/register
Content-Type: application/json

{
  "name": "Test User",
  "email": "testuser@example.com",
  "password": "password123"
}

###

### Duplicate email error
POST http://localhost:8080/api/auth/register
Content-Type: application/json

{
  "name": "Farah Yusni",
  "email": "farah@example.com",
  "password": "password123"
}

###

### Login success
POST http://localhost:8080/api/auth/login
Content-Type: application/json

{
  "email": "admin@example.com",
  "password": "Admin@123"
}

###

### Wrong password error
POST http://localhost:8080/api/auth/login
Content-Type: application/json

{
  "email": "farah@example.com",
  "password": "wrongpassword"
}
