############################################################
# Application Configuration
############################################################

# Name of this Spring Boot application
spring.application.name=support-desk-api

############################################################
# MongoDB Configuration
############################################################

spring.mongodb.host=localhost
spring.mongodb.port=27017
spring.mongodb.database=support_desk_db
spring.mongodb.username=app_user
spring.mongodb.password=abc123
spring.mongodb.authentication-database=support_desk_db

spring.data.mongodb.auto-index-creation=true

############################################################
# Development Settings
############################################################

# Automatically create indexes defined in the model.
# This is useful during development.
spring.data.mongodb.auto-index-creation=true

logging.level.org.springframework.boot.context.properties=TRACE