<<<<<<< HEAD
############################################################
# Application Configuration
############################################################

# Name of this Spring Boot application
spring.application.name=support-desk-api

############################################################
# MongoDB Configuration
############################################################

# MongoDB connection URI
#
# Format:
# mongodb://username:password@host:port/database?authSource=authentication_database
#
# username              : app_user
# password              : abc123
# host                  : localhost
# port                  : 27017
# database              : support_desk_db
# authentication db     : support_desk_db
#
# Since authentication is enabled, Spring Boot must provide
# valid credentials before it can connect.

spring.data.mongodb.uri=mongodb://app_user:abc123@localhost:27017/support_desk_db?authSource=support_desk_db

############################################################
# Development Settings
############################################################

# Automatically create indexes defined in the model.
# This is useful during development.
spring.data.mongodb.auto-index-creation=true
